### PR TITLE
Minus jquery

### PR DESCRIPTION
**Pull request by MathuraMG**
This PR removes the jquery dependencies and library

### CODE REVIEW

**Comment by MathuraMG** [comment]
@lm-n could you have a look?
Also, I have a doubt. Each time we change the library, do we have to change the CDN link?

**Comment by lm-n** [comment]
yes! we have to update the cdn link. Will look at it before we meet tonight!

**Comment by lm-n** [comment]
@MathuraMG Looks good! Can we merge https://github.com/MathuraMG/color-namer/pull/8 and then update the color parts of the library? I can update that on the library and submit a PR but just want to make sure you are on board.

**Comment by MathuraMG** [comment]
Oh yes! Makes sense! I just merged it!

**Comment by lm-n** [comment]
@MathuraMG I've made the changes in PR https://github.com/MathuraMG/p5-accessibility/pull/10

**Pull request merged**
